Done architecture of project.
WWWNasty/Parser-currency pull request #1
Opened 2019-08-05 13:51 UTC by WWWNasty

2019-08-05 19:22 UTC, CodeMonkeyInit requested changes

2019-08-05 19:22 UTC, CodeMonkeyInit commented on BusinessLogicLayer.Abstraction/Interfaces/ICurrencyProvider.cs
> +        Task<IEnumerable<CurrencyDataResponse>> GetAnswerAsync();
Лучше GetExchangeRateAsync

2019-08-05 19:22 UTC, CodeMonkeyInit commented on BusinessLogicLayer.Abstraction/Interfaces/IResponseClient.cs
> +        Task<string> SendMessage(Updates updates);
Лучше SendResponse и потом его придется поменять как появится телеграмм или что-то еще, я думаю его даже не нужно делать универсальным

2019-08-05 19:22 UTC, CodeMonkeyInit commented on BusinessLogicLayer.Implementation/Services/CbrCurrencyProviderService.cs
> +    public class CbrCurrencyProviderService : ICurrencyProvider
Я думаю тут тоже лучше CbrExchangeRateProvider

2019-08-05 19:22 UTC, CodeMonkeyInit commented on BusinessLogicLayer.Implementation/Services/CbrCurrencyProviderService.cs
> +            CbrResponse cbrResponse = await "https://www.cbr-xml-daily.ru/daily_json.js".GetJsonAsync<CbrResponse>();
лучше вынести в конфигурацию

2019-08-05 19:22 UTC, CodeMonkeyInit commented on BusinessLogicLayer.Implementation/Services/CbrCurrencyProviderService.cs
> +//                })
комент удали его

2019-08-05 19:22 UTC, CodeMonkeyInit commented on BusinessLogicLayer.Implementation/Services/CbrCurrencyProviderService.cs
> +                options => options.Items["Date"] = cbrResponse.Date);
Лучше вынести в константу строку "Date"

2019-08-05 19:22 UTC, CodeMonkeyInit commented on BusinessLogicLayer.Implementation/Services/VkResponseClientService.cs
> +    public class VkResponseClientService : IResponseClient
Можно Client убрать

2019-08-05 19:22 UTC, CodeMonkeyInit commented on BusinessLogicLayer.Implementation/Services/VkResponseClientService.cs
> +                case "confirmation":
тоже можно в константу вынести (как и нижний кейс), но не  критично

2019-08-05 19:22 UTC, CodeMonkeyInit commented on BusinessLogicLayer.Implementation/Services/VkResponseClientService.cs
> +                    foreach (CurrencyDataResponse currencyData in currencies)
Можно заменить на Aggregate linq

2019-08-05 19:22 UTC, CodeMonkeyInit commented on BusinessLogicLayer.Objects/Dtos/CbrResponse.cs
> +        public Valute Currencies { get; set; }
Тип тоже можно переименовать в Currencies или CbrCurrencies (так можно избежать конфликтов в namespaces)

2019-08-05 19:22 UTC, CodeMonkeyInit commented on BusinessLogicLayer.Objects/Dtos/Currency.cs
> +        // public override string ToString() => $"Курс {Name}: {Value / Nominal} ₽";
я думаю можно убрать комментарий

2019-08-05 19:22 UTC, CodeMonkeyInit commented on DataAccessLayer.Models/Entities/CurrencyDataResponse.cs
> +    public class CurrencyDataResponse
лучше CurrencyExchangeRate

2019-08-05 19:22 UTC, CodeMonkeyInit commented on DataAccessLayer.Models/Entities/Updates.cs
> +        [JsonProperty("type")]
можно убрать атрибут он ничего не делает

2019-08-05 19:22 UTC, CodeMonkeyInit commented on DataAccessLayer.Models/Entities/Updates.cs
> +        [JsonProperty("object")]
тут тоже

2019-08-05 19:22 UTC, CodeMonkeyInit commented on DataAccessLayer.Models/Entities/Updates.cs
> +    public class Updates
добавь Summary везде

2019-08-05 19:22 UTC, CodeMonkeyInit commented on DataAccessLayer.Models/MapperProfiles/MapperProfiles.cs
> +            //opt => opt.MapFrom(dto => dto.SubCategory.Id)
удали коммент

2019-08-05 19:22 UTC, CodeMonkeyInit commented on DataAccessLayer.Models/MapperProfiles/MapperProfiles.cs
> +    public class MapperProfiles : Profile
лучше ExcangeRateMappingProfile

2019-08-05 19:22 UTC, CodeMonkeyInit commented on DataAccessLayer.Models/MapperProfiles/MapperProfiles.cs
> +    public class MapperProfiles : Profile
*Exchange

2019-08-05 19:22 UTC, CodeMonkeyInit commented on DataAccessLayer.Models/MapperProfiles/MapperProfiles.cs
> +    public class DateResolver : IValueResolver<Currency, CurrencyDataResponse, DateTime>
вынеси в отдельный файл

2019-08-05 19:22 UTC, CodeMonkeyInit commented on DataAccessLayer.Models/MapperProfiles/MapperProfiles.cs
> +            context.Items["Date"] as DateTime? ?? DateTime.Today;
Тут замени на константу которую создала выше

2019-08-16 17:32 UTC, WWWNasty commented on BusinessLogicLayer.Implementation/Services/CbrCurrencyProviderService.cs
> +                options => options.Items["Date"] = cbrResponse.Date);
no actual inav

2019-08-19 06:57 UTC, merged